--------------------------------------------------------
--  DDL for Table OFFICES
--------------------------------------------------------

  CREATE TABLE "MIGRANT"."OFFICES" 
   (	"ID" NUMBER(10,0), 
	"CITY" VARCHAR2(15 CHAR), 
	"REGION" VARCHAR2(10 CHAR), 
	"SALES" NUMBER(38,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010464
--------------------------------------------------------

  CREATE UNIQUE INDEX "MIGRANT"."SYS_C0010464" ON "MIGRANT"."OFFICES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table OFFICES
--------------------------------------------------------

  ALTER TABLE "MIGRANT"."OFFICES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "MIGRANT"."OFFICES" MODIFY ("CITY" NOT NULL ENABLE);
  ALTER TABLE "MIGRANT"."OFFICES" MODIFY ("REGION" NOT NULL ENABLE);
  ALTER TABLE "MIGRANT"."OFFICES" MODIFY ("SALES" NOT NULL ENABLE);
  ALTER TABLE "MIGRANT"."OFFICES" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
