---
---  CREATE TABLE statements for Oracle
---
--TODO -- ID ORDER
create database Exec_control;
use  Exec_control;

DROP TABLE ORDERS_CART;
DROP TABLE ORDERS;
DROP TABLE CUSTOMERS;
DROP TABLE SALESREPS;
DROP TABLE OFFICES;
DROP TABLE PRODUCTS;


CREATE TABLE PRODUCTS
     (
		ID CHAR(5) NOT NULL,
		DESCRIPTION VARCHAR(20) NOT NULL,
		PRICE DECIMAL(9,2) NOT NULL,
		AVAIL INTEGER NOT NULL,
		PRIMARY KEY (ID));


CREATE TABLE OFFICES
     (	
		ID INTEGER NOT NULL,
        CITY VARCHAR(15) NOT NULL,
		REGION VARCHAR(10) NOT NULL,
		SALES DECIMAL(9,2) NOT NULL,
		PRIMARY KEY (ID));


CREATE TABLE SALESREPRS
   (	
		ID INTEGER NOT NULL,
        NAME VARCHAR(15) NOT NULL,
        AGE INTEGER,
		OFFICE INTEGER,
		POSITION VARCHAR(10) , 
		HIRE_DATE DATE NOT NULL,
		MANAGER INTEGER,
		SALES DECIMAL(9,2) NOT NULL,
		PRIMARY KEY (ID),
		FOREIGN KEY (MANAGER) REFERENCES SALESREPRS(ID) ON DELETE NO ACTION,
		CONSTRAINT WORKSIN FOREIGN KEY (OFFICE) REFERENCES OFFICES(ID) ON DELETE SET NULL);


CREATE TABLE CUSTOMERS
   (
	CUST_NUM INTEGER    NOT NULL,
    COMPANY  VARCHAR(20) NOT NULL,
    CUST_REP INTEGER,
    CREDIT_LIMIT DECIMAL(9,2),
	PRIMARY KEY (CUST_NUM),
	CONSTRAINT HASREP FOREIGN KEY (CUST_REP)
	REFERENCES SALESREPRS(ID) ON DELETE SET NULL);


CREATE TABLE ORDERS
  (	
	 id integer primary key AUTOINCREMENT not null,
    CUST INTEGER NOT NULL,
    REPRES INTEGER,
    TOTAL_COST DECIMAL(9) NOT NULL DEFAULT 0,
	ORDER_DATE DATE NOT NULL,
	PLANNED_D_DAY DATE  NOT NULL,
	PAY_DATE DATE DEFAULT NULL,
	CUST_CONFIRM DATE DEFAULT NULL,
	SENDED DATE DEFAULT NULL,
	ENTER_COUNTR DATE DEFAULT NULL,
	POST_OFICE DATE DEFAULT NULL,
	DELIVERED DATE DEFAULT NULL,
	CONSTRAINT PLACEDBY FOREIGN KEY (CUST) REFERENCES CUSTOMERS(CUST_NUM) ON DELETE CASCADE,
	CONSTRAINT TAKENBY FOREIGN KEY (REPRES) REFERENCES SALESREPRS(ID) ON DELETE SET NULL
	);

CREATE TABLE ORDERS_CART(
	ORD_ID int,
	PROD_ID CHAR(5) NOT NULL,
	PROD_COUNT INT,
	CONSTRAINT ISFOR FOREIGN KEY (PROD_ID) REFERENCES PRODUCTS(ID),
	CONSTRAINT ORDER_FOR FOREIGN KEY (ORD_ID) REFERENCES ORDERS(ID)
);