//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAB_02
{
    using System;
    using System.Collections.Generic;
    
    public partial class DELIVERED_ORDERS
    {
        public string ID { get; set; }
        public string PRODUCT { get; set; }
        public int CUST { get; set; }
        public System.DateTime ORDER_DATE { get; set; }
        public Nullable<System.DateTime> DELIVERED { get; set; }
    }
}
