//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAB_02
{
    using System;
    using System.Collections.Generic;
    
    public partial class gadm36_blr_0
    {
        public int ogr_fid { get; set; }
        public System.Data.Entity.Spatial.DbGeometry ogr_geometry { get; set; }
        public string gid_0 { get; set; }
        public string name_0 { get; set; }
    }
}
