//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAB_02
{
    using System;
    using System.Collections.Generic;
    
    public partial class gadm36_blr_1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public gadm36_blr_1()
        {
            this.OFFICES = new HashSet<OFFICES>();
        }
    
        public int ogr_fid { get; set; }
        public System.Data.Entity.Spatial.DbGeometry ogr_geometry { get; set; }
        public string gid_0 { get; set; }
        public string name_0 { get; set; }
        public string gid_1 { get; set; }
        public string name_1 { get; set; }
        public string varname_1 { get; set; }
        public string nl_name_1 { get; set; }
        public string type_1 { get; set; }
        public string engtype_1 { get; set; }
        public string cc_1 { get; set; }
        public string hasc_1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OFFICES> OFFICES { get; set; }
    }
}
