//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAB_02
{
    using System;
    using System.Collections.Generic;
    
    public partial class geometry_columns
    {
        public string f_table_catalog { get; set; }
        public string f_table_schema { get; set; }
        public string f_table_name { get; set; }
        public string f_geometry_column { get; set; }
        public int coord_dimension { get; set; }
        public int srid { get; set; }
        public string geometry_type { get; set; }
    }
}
