//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAB_02
{
    using System;
    using System.Collections.Generic;
    
    public partial class managers
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> AGE { get; set; }
        public Nullable<int> OFFICE { get; set; }
        public string POSITION { get; set; }
        public System.DateTime HIRE_DATE { get; set; }
        public Nullable<int> MANAGER { get; set; }
        public decimal SALES { get; set; }
    }
}
