//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAB_02
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFFICES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OFFICES()
        {
            this.SALESREPRS = new HashSet<SALESREPRS>();
        }
    
        public int ID { get; set; }
        public string CITY { get; set; }
        public string REGION { get; set; }
        public decimal SALES { get; set; }
        public Nullable<int> position { get; set; }
    
        public virtual gadm36_blr_1 gadm36_blr_1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALESREPRS> SALESREPRS { get; set; }
    }
}
