//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAB_02
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDERS()
        {
            this.ORDERS_CART = new HashSet<ORDERS_CART>();
        }
    
        public int ID { get; set; }
        public int CUST { get; set; }
        public Nullable<int> REPRES { get; set; }
        public decimal TOTAL_COST { get; set; }
        public System.DateTime ORDER_DATE { get; set; }
        public System.DateTime PLANNED_D_DAY { get; set; }
        public Nullable<System.DateTime> PAY_DATE { get; set; }
        public Nullable<System.DateTime> CUST_CONFIRM { get; set; }
        public Nullable<System.DateTime> SENDED { get; set; }
        public Nullable<System.DateTime> ENTER_COUNTR { get; set; }
        public Nullable<System.DateTime> POST_OFICE { get; set; }
        public Nullable<System.DateTime> DELIVERED { get; set; }
    
        public virtual CUSTOMERS CUSTOMERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDERS_CART> ORDERS_CART { get; set; }
        public virtual SALESREPRS SALESREPRS { get; set; }
    }
}
