//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAB_02
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTS
    {
        public string ID { get; set; }
        public string DESCRIPTION { get; set; }
        public decimal PRICE { get; set; }
        public int AVAIL { get; set; }
    
        public virtual ORDERS_CART ORDERS_CART { get; set; }
    }
}
